business/urls.py
from django.urls import path
from .views import (ProjectList,
                    ProjectDetail,
                    DocumentCreate,
                    TaskList,
                    TaskDetail,
                    ProjectCreate,
                    EventCreate,
                    ProjectUpdate,
                    ProjectDelete,
                    EventDetail,
                    EventList,
                    EventUpdate,
                    EventDelete,
                    TaskCreate,
                    TaskUpdate,
                    TaskDelete,
                    task_set_done)

app_name = 'business'
urlpatterns = [
    path('projects/', ProjectList.as_view(), name='projects'),
    path('projects/new/', ProjectCreate.as_view(), name='project-create'),
    path('docs/new/', DocumentCreate.as_view(), name='document-create'),
    path('projects/<int:pk>/', ProjectDetail.as_view(), name='project-detail'),
    path('projects/<int:pk>/update/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', ProjectDelete.as_view(), name='project-delete'),
    path('events/', EventList.as_view(), name='events'),
    path('events/new/', EventCreate.as_view(), name='event-create'),
    path('events/<int:pk>/', EventDetail.as_view(), name='event-detail'),
    path('events/<int:pk>/update/', EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', EventDelete.as_view(), name='event-delete'),
    path('tasks/', TaskList.as_view(), name='task-list'),
    path('tasks/new/', TaskCreate.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetail.as_view(), name='task-detail'),
    path('tasks/<int:pk>/update', TaskUpdate.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete', TaskDelete.as_view(), name='task-delete'),
    path('tasks/<int:task_id>/done', task_set_done, name='task-done')
]

leadbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('leads.urls')),
    path('business/', include('business.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.CompanyList.as_view(), name='companies'),
    path('new/', views.CompanyCreate.as_view(), name='companies-create'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='companies-update'),
    path('<int:pk>/', views.CompanyDetail.as_view(), name='detail'),
    path('people/<int:pk>/', views.PersonDetail.as_view(), name='person-detail'),
    path('people/new/', views.PersonCreate.as_view(), name='person-create'),
    path('people/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('phone/new/', views.PhoneCreate.as_view(), name='phone-create'),
    path('email/new/', views.EmailCreate.as_view(), name='email-create'),
]

leads/models.py
from django.db import models
from django.utils import timezone
from inventory.models import Discount
from django.shortcuts import reverse
from accounts.models import User
from datetime import timedelta
from time import time


class PersonRole(models.TextChoices):
    UNKNOWN = 'UNW', 'Неизвестно'
    GENERAL_MANAGER = "CEO", "Генеральный директор"
    EXECUTIVE_DIRECTOR = "EXD", "Исполнительный директор"
    CHIEF_TECHNICAL_OFFICER = "CTO", "Технический директор"
    DEPUTY_DIRECTOR = "DPD", "Заместитель директора"
    DIRECTOR = "DIR", "Директор"
    SALES_DIRECTOR = "SAD", "Директор по продажам"
    HEAD_OF_DEPARTMENT = " ", "Руководитель отдела"
    CHIEF_TECHNICAL_ENGINEER = "CTE", "Главный инженер"
    ENGINEER = "ENG", "Инженер"
    CONSTRUCTOR = "CNS", "Конструктор"
    DESIGNER = "DES", "Проектировщик"
    EXPERT = "EXP", "Эксперт"
    PURCHASING_SPECIALIST = "PUR", "Специалист закупки"
    PROGRAMMER = "PRG", "Программист"
    SALESMAN = "SAL", "Продавец"
    KEY_ACCOUNT_MANAGER = "KAM", "Ключевой менеджер по работе с Bosch"
    PARTNER_MANAGER = "MAN", "Менеджер по работе с партнерами"


class Person(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    # role_choices = (
    #     ("Директор", "Директор"),
    #     ("Генеральный директор", "Генеральный директор"),
    #     ("Исполнительный директор", "Исполнительный директор"),
    #     ("Руководитель отдела", "Руководитель отдела"),
    #     ("Инженер", "Инженер"),
    #     ("Специалист закупки", "Специалист закупки"),
    #     ("Программист", "Программист"),
    #     ("Продавец", "Продавец"),
    #     ("Ключевой менеджер по работе с Bosch", "Ключевой менеджер по работе с Bosch"),
    # )

    role = models.CharField(max_length=3, null=True, choices=PersonRole.choices, default=PersonRole.UNKNOWN)
    description = models.TextField(max_length=500, null=True, blank=True, help_text="Особенности работы с контрагентом")

    # foreign keys
    company = models.ForeignKey("Company", null=True, on_delete=models.SET_NULL)
    is_main_contact = models.BooleanField(default=False)

    def save(self, *args, **kwargs):

        # Making sure there is only one main person for a company
        if self.is_main_contact:
            try:
                old_main_contact = Person.objects.get(company=self.company, is_main_contact=True)
                if self != old_main_contact:
                    old_main_contact.is_main_contact = False
                    old_main_contact.save()
            except Person.DoesNotExist:
                pass

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.id])

    def get_email(self):
        emails = Email.objects.filter(person=self)
        for email in emails:
            if email.type == "MAIN":
                return email
        return emails.first()

    def get_phone(self):
        phones = Phone.objects.filter(person=self)
        for phone in phones:
            if phone.type == "MAIN":
                return phone
        return phones.first()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Company(models.Model):
    title = models.CharField(max_length=150)
    title_latin = models.CharField(max_length=50, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    about = models.TextField(max_length=5000, null=True)
    date_created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey("accounts.User", on_delete=models.SET_DEFAULT, default=User.objects.get(pk=3).pk, related_name="company_creator")

    # foreign keys
    legal_form = models.ForeignKey("LegalForm", null=True, on_delete=models.SET_NULL)

    # status = models.ForeignKey("CompanyStatus", on_delete=models.SET_NULL, null=True)
    status_choices = (
        ("ACT_LOY", "Active customer (loyal)"),
        ("ACT_DIS", "Active customer (disloyal)"),
        ("POT_LOY", "Potential customer (loyal)"),
        ("POT_CON", "Potential customer (in contact)"),
        ("POT_UNK", "Potential customer (not in contact)"),
        ("CMP_USF", "Competitor (useless)"),
        ("CMP_USL", "Competitor (useful)"),
        ("UNKNOWN", "Unknown"),
        ("BLOCKED", "Blocked")
    )
    status = models.CharField(max_length=7, choices=status_choices, default="UNKNOWN")
    discounts = models.ManyToManyField("inventory.Discount", help_text="Hold down “Control”, or “Command” on a Mac, "
                                                                       "to select more than one.")  # TODO: add project discount
    partners = models.ManyToManyField('self', blank=True)
    manager = models.ForeignKey("accounts.User", null=True, on_delete=models.SET_NULL, related_name="company_manager")

    class Meta:
        unique_together = (("title", "legal_form"),)

    def get_absolute_url(self):
        return reverse("leads:detail", args=[self.id])

    def __str__(self):
        return f"{self.title}"

    def get_main_contact(self):
        try:
            return self.person_set.get(is_main_contact=True)
        except Person.DoesNotExist:
            return None

    def get_phone(self):
        if self.get_main_contact():
            if self.get_main_contact().get_phone():
                return self.get_main_contact().get_phone()
        else:
            emps = self.person_set.all()  # Get all employees
            for emp in emps:
                if emp.get_phone():
                    phone = emp.get_phone()
                    return phone

    def get_email(self):
        if self.get_main_contact():
            if self.get_main_contact().get_email():
                return self.get_main_contact().get_email()
        else:
            emps = self.person_set.all()  # Get all employees
            for emp in emps:
                if emp.get_email():
                    email = emp.get_email()
                    return email

    def get_short_status(self):
        status = self.get_status_display().split(" ")[0]
        if status == "Active":
            color = "success"
        elif status == "Potential":
            color = "warning"
        else:
            color = "danger"
        return {"status": status, "color": color}

    @staticmethod
    def get_hot_leads(user):
        # return companies that need to be contacted

        # In a tuple: first value for new leads, second value for old leads in days
        events_frequency = {
            "ACT_LOY": (5, 45),
            "ACT_DIS": (5, 30),
            "POT_LOY": (5, 20),
            "POT_CON": (10, 45),
            "POT_UNK": (5, 45),
            "CMP_USF": (5, 45)
        }

        user_leads = Company.objects.filter(manager=user)

        hot_ids = []
        for lead in user_leads:
            if lead.status in events_frequency.keys():
                last_event_delta = timezone.now() - (lead.event_set.last().date if lead.event_set.count() else lead.date_created)
                if (timezone.now() - lead.date_created) > timedelta(days=90):
                    normal_frequency = events_frequency[lead.status][1]
                else:
                    normal_frequency = events_frequency[lead.status][0]

                if last_event_delta > timedelta(days=normal_frequency):
                    hot_ids.append(lead.id)

        print(user_leads.filter(id__in=hot_ids))
        return user_leads.filter(id__in=hot_ids)


# class CompanyStatus(models.Model):
#     status_choices = (
#         ("Unknown", "Unknown"),
#         ("Active", "Active"),
#         ("Inactive", "Inactive"),
#         ("Blocked", "Blocked"),
#         ("Competitor", "Competitor")
#     )
#     status = models.CharField(max_length=45, choices=status_choices, default=status_choices[0])
#
#     def __str__(self):
#         return self.status


class LegalForm(models.Model):
    short_form = models.CharField(max_length=15)
    long_form = models.CharField(max_length=50)

    def __str__(self):
        return self.short_form


class ContactType(models.TextChoices):
    MAIN = "MAIN", "main"
    MOBILE = "MOB", "mobile"
    WORK = "WRK", "work"
    PERSONAL = "PRS", "personal"
    PAST = "PST", "past"


class Email(models.Model):
    email = models.EmailField(max_length=255)
    type = models.CharField(max_length=4, choices=ContactType.choices, default=ContactType.MAIN)

    # foreign keys
    person = models.ForeignKey("Person", on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey("Company", on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.person.id])

    def __str__(self):
        return self.email


class Phone(models.Model):
    country_code = models.CharField(max_length=3)
    area_code = models.CharField(max_length=7)
    number = models.CharField(max_length=20)
    extension = models.CharField(max_length=20, null=True, blank=True)
    type = models.CharField(max_length=4, choices=ContactType.choices, default=ContactType.MAIN)

    # foreign keys
    # type = models.ForeignKey("ContactType", on_delete=models.SET_NULL, null=True)
    person = models.ForeignKey("Person", on_delete=models.CASCADE)
    company = models.ForeignKey("Company", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = (("country_code", "area_code", "number", "extension"),)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.person.id])

    def __str__(self):
        phone = f"{self.country_code}{self.area_code}{self.number}"
        if self.extension:
            phone += f",{self.extension}"
        return phone
        # number_text = str(self.number)
        # return f"+{self.country_code} ({self.area_code}) {number_text[:3]}-{number_text[3:5]}-{number_text[5:]} :" \
        #        f" {self.person.first_name} {self.person.last_name} ({self.type})"

leads/forms.py
from django import forms
from .models import Phone


class PhoneCreateForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = "__all__"
        labels = {
            'country_code': '',
            'area_code': '',
            'number': '',
            'extension': ''
        }
        help_texts = {
            'area_code': 'code.',
            'number': 'number',
            'extension': 'extension',
        }

leads/templates/leads/company_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% include 'dashboard/form_snippet.html' with title='New Company' %}
{% endblock content %}

leads/templates/leads/company_list.html
{% extends 'dashboard/base.html' %}
{% block content %}
<form method="GET" class="form-inline d-flex md-form mr-auto mb-2 form-sm mt-0">
    <input type="search" id="site-search" name="q" placeholder="Search" {% if q %} value="{{ q }}"{% endif %} aria-label="Search" class="form-control flex-fill w-auto">
<!--    <a href="{% url 'leads:companies' %}?manager={{ user.pk }}" class="btn btn-outline-info ml-2">only mine</a>-->
    <a href="{% url 'leads:companies-create' %}" class="btn btn-outline-info ml-2" data-toggle="tooltip" data-placement="right" title="Add new company">
        create
        <!--        <svg xmlns="http://www.w3.org/2000/svg" width="1.7em" height="1.7em" fill="currentColor" class="bi bi-plus-circle-fill text-info" viewBox="0 0 16 16">-->
        <!--            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>-->
        <!--        </svg>-->
    </a>
</form>
{% if not company_list %}
<div class="content-section">
    <h4>You don't have any companies yet.</h4>
    <p>
        Fill free to <a href="{% url 'leads:companies-create' %}">create</a> new!
    </p>
</div>
{% else %}
<table class="table table-hover content-section">
    <thead>
    <tr>
        <th scope="col">Company</th>
        <th scope="col" class="hide">Contact</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    {% for company in company_list %}
    <tr>
        <td scope="row"><a href="{% url 'leads:detail' company.pk %}" class="text-dark">{{ company.title }}, {{ company.legal_form }}</a></td>
        <td>
            {% if company.get_main_contact %}
            <a href="{% url 'leads:person-detail' company.get_main_contact.pk %}" class="text-secondary">
                {{ company.get_main_contact }}
            </a>
            {% elif company.person_set.all %}
            <a href="{% url 'leads:person-detail' company.person_set.all.first.pk %}" class="text-secondary">
                {{ company.person_set.all.first }}
            </a>
            {% endif %}
        </td>
        <td class="hide">
            <span class="text-{{ company.get_short_status.color }}">{{ company.get_short_status.status }}</span>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endif %}
{% if is_paginated %}
<hr>
{% if page_obj.has_previous %}
<a class="btn btn-outline-secondary mb-4" href="?page=1&q={{ q }}&hot={{ hot }}">First</a>
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}&q={{ q }}&hot={{ hot }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-secondary mb-4" href="?page={{ num }}&q={{ q }}&hot={{ hot }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-secondary mb-4" href="?page={{ num }}&q={{ q }}&hot={{ hot }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}&q={{ q }}&hot={{ hot }}">Next</a>
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}&q={{ q }}&hot={{ hot }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}

leads/templates/leads/email_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% include 'dashboard/form_snippet.html' with title='New Email' %}
{% endblock content %}

leads/templates/leads/leads.html
{% extends 'dashboard/base.html' %}
{% block content %}
<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">Company</th>
    <th scope="col">Legal form</th>
    <th scope="col">Contact</th>
    <th scope="col">In partnership</th>
  </tr>
  </thead>
  <tbody>
  {% for company in companies_list %}
  <tr>
    <th scope="row">{{ company.id }}</th>
    <td><a href="{% url 'leads:detail' company.pk %}">{{ company.title }}</a></td>
    <td>{{ company.legal_form }}</td>
    <td><a href="#" class="text-secondary">{{ company.person_set.all.first }}</a></td>
    <td>{{ company.status }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}

leads/templates/leads/person_detail.html
{% extends 'dashboard/base.html' %}
{% block content %}
<article class="media content-section">
    {% load static %}
    <img class="rounded-circle article-img" src="{% static 'dashboard/img/default_profile_img.png' %}">
    <div class="media-body">
        <!--        <div class="article-metadata">-->
        <!--          <a class="mr-2" href="{% url 'leads:companies' %}">←</a><small class="text-muted">Company Profile</small>-->
        <!--        </div>-->
        <h2>{{ person.first_name }} {{ person.last_name }}
            <a href="{% url 'leads:person-update' person.pk %}" class="btn btn-outline-info float-right">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                </svg>
            </a>
        </h2>
        <small class="text-muted"><a href="{% url 'leads:detail' person.company.pk %}" class="text-muted">{{ person.company }}</a> ({{ person.get_role_display }})</small>
        <p class="mt-3 mb-4">
            {% if person.description %}
            {{ person.description|linebreaks }}
            {% endif %}
        </p>
        <strong>Email</strong>
        <a href="{% url 'leads:email-create' %}?person={{ person.id }}&company={{ person.company.id }}" class="ml-2" type="submit">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </a>
        {% if person.email_set.all %}
        <ul class="list-unstyled">
            {% for email in person.email_set.all %}
            <li><a href="mailto:{{ email.email }}">{{ email.email }}</a></li>
            {% endfor %}
        </ul>
        {% endif %}
        <hr>
        <strong>Phone</strong>
        <a href="{% url 'leads:phone-create' %}?person={{ person.id }}&company={{ person.company.id }}" class="ml-2" type="submit">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </a>
        {% if person.phone_set.all %}
        <ul class="list-unstyled">
            {% for phone in person.phone_set.all %}
            <span class="text-muted">{{ phone.get_type_display }}</span><li class="text-secondary"><a href="tel:+{{ phone }}">
            +{{ phone.country_code }} ({{ phone.area_code }}) {{ phone.number }}{% if phone.extension %} ({{ phone.extension }}){% endif %}
        </a></li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</article>
<article class="media content-section">
    <div class="media-body">
        <strong>History</strong>
        <a href="{% url 'business:event-create' %}?company={{ person.company.id }}&person={{ person.pk }}" class="ml-2" type="submit">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </a>
        {% if person.event_set.count %}
        <div class="mt-1 mr-5">
            <ul class="timeline">
                {% for event in person.event_set.all reversed %}
                <li>
                    <a href="{% url 'business:event-detail' event.pk %}">{{ event.get_title_display }}</a>
                    <a href="{% url 'business:event-update' event.pk %}" class="ml-3 text-info history">
                        <svg width="0.9em" height="0.9em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                        </svg>
                    </a>
                    <a href="{% url 'business:event-delete' event.pk %}" class="ml-3 text-danger history">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                    </a>
                    <span class="float-right text-muted">{{ event.date|date:'F d, Y' }}</span>
                    <p style="white-space: nowrap;">{{ event.description|linebreaks }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
</article>
{% endblock content %}

leads/templates/leads/person_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% include 'dashboard/form_snippet.html' with title='New Person' %}
{% endblock content %}

leads/templates/leads/phone_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ title }}</legend>
        <div class="mb-1">Phone number*</div>
        <div class="form-row">
            <div class="form-group col-1 mb-0">
                {{ form.country_code|as_crispy_field }}
            </div>
            <div class="form-group col-2 mb-0 ml-1">
                {{ form.area_code|as_crispy_field }}
            </div>
            <div class="form-group col-3 mb-0">
                {{ form.number|as_crispy_field }}
            </div>
            <div class="form-group col-2 mb-0">
                {{ form.extension|as_crispy_field }}
            </div>
        </div>
        {{ form.type|as_crispy_field }}
        {{ form.person|as_crispy_field }}
        {{ form.company|as_crispy_field }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Save</button>
    </div>
</form>
{% endblock content %}