accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import register, profile, UserUpdate

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('<int:pk>/update/', UserUpdate.as_view(), name='update'),
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="accounts/logout.html"), name='logout')
]

leadbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('leads.urls')),
    path('business/', include('business.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.CompanyList.as_view(), name='companies'),
    path('new/', views.CompanyCreate.as_view(), name='companies-create'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='companies-update'),
    path('<int:pk>/', views.CompanyDetail.as_view(), name='detail'),
    path('people/<int:pk>/', views.PersonDetail.as_view(), name='person-detail'),
    path('people/new/', views.PersonCreate.as_view(), name='person-create'),
    path('people/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('phone/new/', views.PhoneCreate.as_view(), name='phone-create'),
    path('email/new/', views.EmailCreate.as_view(), name='email-create'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


def user_image_path(instance, filename):
    return f"users/{instance.pk}/profile_img/{filename}"


class User(AbstractUser):
    profile_img = models.ImageField(default="users/default_profile_img.png", upload_to=user_image_path)
    widgets = models.ManyToManyField("dashboard.Widget")

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class UserRegisterForm(UserCreationForm):
    fields = forms.EmailField

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserRegisterForm
from django.views.generic import UpdateView
from .models import User


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            form.save()
            message = messages.success(request, f"User {username} has been created successfully")
            return redirect("dashboard:home")
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {"form": form})


@login_required
def profile(request):
    return render(request, "accounts/profile.html")


class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "email", "profile_img", "widgets"]
    success_url = reverse_lazy("accounts:profile")


# class RegisterView(View):
#     def get(self, request):
#         form = UserRegister
#         return render(request, 'accounts/register.html', {"form": form})
#
#     def post(self, request):
#         form = UserRegister(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get("username")
#             form.save()
#             message = messages.success(request, f"User {username} created successfully")
#             return redirect("home")
#         return render(request, 'accounts/register.html', {"form": form})

accounts/templates/accounts/login.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Login</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'accounts:register' %}">Sign Up Now</a>
        </small>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends "dashboard/base.html" %}
{% block content %}
<h2>You have been logged out</h2>
<div class="border-top pt-3">
    <small class="text-muted">
        <a href="{% url 'accounts:login' %}">Log In Again</a>
    </small>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'dashboard/base.html' %}
{% block content %}
<article class="media content-section p-4">
    <img class="rounded-circle profile-img" src="{{ user.profile_img.url }}">
    <div class="media-body">
        <h2>{{ user.first_name }} {{ user.last_name }}
            <a href="{% url 'accounts:update' user.pk %}" class="btn btn-outline-info float-right">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                </svg>
            </a>
        </h2>
        <small class="text-muted"><span class="text-muted">@{{ user.username }}</span></small>
        <hr>
        <p class="text-secondary">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
            </svg>
            {{ user.email }}
        </p>
        <a class="text-info" href="{% url 'accounts:logout' %}">Logout</a>
    </div>
</article>
<!--    {% if user == object.author %}-->
<div>
    <a class="btn btn-outline-secondary" href="#">Update</a>
    <a class="btn btn-outline-danger" href="#">Delete</a>
</div>
<!--    {% endif %}-->
{% endblock content %}

accounts/templates/accounts/register.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/user_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile</legend>
            {% load crispy_forms_tags %}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>
{% endblock content %}