accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import register, profile, UserUpdate

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('<int:pk>/update/', UserUpdate.as_view(), name='update'),
    path('login/', LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', LogoutView.as_view(template_name="accounts/logout.html"), name='logout')
]

business/urls.py
from django.urls import path
from .views import (ProjectList,
                    ProjectDetail,
                    DocumentCreate,
                    TaskList,
                    TaskDetail,
                    ProjectCreate,
                    EventCreate,
                    ProjectUpdate,
                    ProjectDelete,
                    EventDetail,
                    EventList,
                    EventUpdate,
                    EventDelete,
                    TaskCreate,
                    TaskUpdate,
                    TaskDelete,
                    task_set_done)

app_name = 'business'
urlpatterns = [
    path('projects/', ProjectList.as_view(), name='projects'),
    path('projects/new/', ProjectCreate.as_view(), name='project-create'),
    path('docs/new/', DocumentCreate.as_view(), name='document-create'),
    path('projects/<int:pk>/', ProjectDetail.as_view(), name='project-detail'),
    path('projects/<int:pk>/update/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', ProjectDelete.as_view(), name='project-delete'),
    path('events/', EventList.as_view(), name='events'),
    path('events/new/', EventCreate.as_view(), name='event-create'),
    path('events/<int:pk>/', EventDetail.as_view(), name='event-detail'),
    path('events/<int:pk>/update/', EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', EventDelete.as_view(), name='event-delete'),
    path('tasks/', TaskList.as_view(), name='task-list'),
    path('tasks/new/', TaskCreate.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetail.as_view(), name='task-detail'),
    path('tasks/<int:pk>/update', TaskUpdate.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete', TaskDelete.as_view(), name='task-delete'),
    path('tasks/<int:task_id>/done', task_set_done, name='task-done')
]

dashboard/urls.py
from django.urls import path
from . import views
from leads.views import CompanyList

app_name = 'dashboard'
urlpatterns = [
    path('', views.Dashboard.as_view(), name='home'),
    path('site-search/', CompanyList.as_view(), name='site-search'),
    path('settings/', views.settings, name='settings')
]

leadbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('leads.urls')),
    path('business/', include('business.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.CompanyList.as_view(), name='companies'),
    path('new/', views.CompanyCreate.as_view(), name='companies-create'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='companies-update'),
    path('<int:pk>/', views.CompanyDetail.as_view(), name='detail'),
    path('people/<int:pk>/', views.PersonDetail.as_view(), name='person-detail'),
    path('people/new/', views.PersonCreate.as_view(), name='person-create'),
    path('people/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('phone/new/', views.PhoneCreate.as_view(), name='phone-create'),
    path('email/new/', views.EmailCreate.as_view(), name='email-create'),
]

dashboard/models.py
from django.db import models


class Widget(models.Model):

    class WidgetSize(models.IntegerChoices):
        SINGLE = (1, "Single")
        DOUBLE = (2, "Double")
        QUADRUPLE = (4, "Quadruple")

    title = models.CharField(max_length=20)
    description = models.CharField(max_length=50, null=True, blank=True)
    url_path_name = models.CharField(max_length=100, default='dashboard:home')
    size = models.IntegerField(choices=WidgetSize.choices, default=WidgetSize.SINGLE)

    def save(self, *args, **kwargs):
        self.title = self.title.lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

leads/models.py
from django.db import models
from django.utils import timezone
from inventory.models import Discount
from django.shortcuts import reverse
from accounts.models import User
from datetime import timedelta
from time import time


class PersonRole(models.TextChoices):
    UNKNOWN = 'UNW', 'Неизвестно'
    GENERAL_MANAGER = "CEO", "Генеральный директор"
    EXECUTIVE_DIRECTOR = "EXD", "Исполнительный директор"
    CHIEF_TECHNICAL_OFFICER = "CTO", "Технический директор"
    DEPUTY_DIRECTOR = "DPD", "Заместитель директора"
    DIRECTOR = "DIR", "Директор"
    SALES_DIRECTOR = "SAD", "Директор по продажам"
    HEAD_OF_DEPARTMENT = " ", "Руководитель отдела"
    CHIEF_TECHNICAL_ENGINEER = "CTE", "Главный инженер"
    ENGINEER = "ENG", "Инженер"
    CONSTRUCTOR = "CNS", "Конструктор"
    DESIGNER = "DES", "Проектировщик"
    EXPERT = "EXP", "Эксперт"
    PURCHASING_SPECIALIST = "PUR", "Специалист закупки"
    PROGRAMMER = "PRG", "Программист"
    SALESMAN = "SAL", "Продавец"
    KEY_ACCOUNT_MANAGER = "KAM", "Ключевой менеджер по работе с Bosch"
    PARTNER_MANAGER = "MAN", "Менеджер по работе с партнерами"


class Person(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)

    # role_choices = (
    #     ("Директор", "Директор"),
    #     ("Генеральный директор", "Генеральный директор"),
    #     ("Исполнительный директор", "Исполнительный директор"),
    #     ("Руководитель отдела", "Руководитель отдела"),
    #     ("Инженер", "Инженер"),
    #     ("Специалист закупки", "Специалист закупки"),
    #     ("Программист", "Программист"),
    #     ("Продавец", "Продавец"),
    #     ("Ключевой менеджер по работе с Bosch", "Ключевой менеджер по работе с Bosch"),
    # )

    role = models.CharField(max_length=3, null=True, choices=PersonRole.choices, default=PersonRole.UNKNOWN)
    description = models.TextField(max_length=500, null=True, blank=True, help_text="Особенности работы с контрагентом")

    # foreign keys
    company = models.ForeignKey("Company", null=True, on_delete=models.SET_NULL)
    is_main_contact = models.BooleanField(default=False)

    def save(self, *args, **kwargs):

        # Making sure there is only one main person for a company
        if self.is_main_contact:
            try:
                old_main_contact = Person.objects.get(company=self.company, is_main_contact=True)
                if self != old_main_contact:
                    old_main_contact.is_main_contact = False
                    old_main_contact.save()
            except Person.DoesNotExist:
                pass

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.id])

    def get_email(self):
        emails = Email.objects.filter(person=self)
        for email in emails:
            if email.type == "MAIN":
                return email
        return emails.first()

    def get_phone(self):
        phones = Phone.objects.filter(person=self)
        for phone in phones:
            if phone.type == "MAIN":
                return phone
        return phones.first()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Company(models.Model):
    title = models.CharField(max_length=150)
    title_latin = models.CharField(max_length=50, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    about = models.TextField(max_length=5000, null=True)
    date_created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey("accounts.User", on_delete=models.SET_DEFAULT, default=User.objects.get(pk=3).pk, related_name="company_creator")

    # foreign keys
    legal_form = models.ForeignKey("LegalForm", null=True, on_delete=models.SET_NULL)

    # status = models.ForeignKey("CompanyStatus", on_delete=models.SET_NULL, null=True)
    status_choices = (
        ("ACT_LOY", "Active customer (loyal)"),
        ("ACT_DIS", "Active customer (disloyal)"),
        ("POT_LOY", "Potential customer (loyal)"),
        ("POT_CON", "Potential customer (in contact)"),
        ("POT_UNK", "Potential customer (not in contact)"),
        ("CMP_USF", "Competitor (useless)"),
        ("CMP_USL", "Competitor (useful)"),
        ("UNKNOWN", "Unknown"),
        ("BLOCKED", "Blocked")
    )
    status = models.CharField(max_length=7, choices=status_choices, default="UNKNOWN")
    discounts = models.ManyToManyField("inventory.Discount", help_text="Hold down “Control”, or “Command” on a Mac, "
                                                                       "to select more than one.")  # TODO: add project discount
    partners = models.ManyToManyField('self', blank=True)
    manager = models.ForeignKey("accounts.User", null=True, on_delete=models.SET_NULL, related_name="company_manager")

    class Meta:
        unique_together = (("title", "legal_form"),)

    def get_absolute_url(self):
        return reverse("leads:detail", args=[self.id])

    def __str__(self):
        return f"{self.title}"

    def get_main_contact(self):
        try:
            return self.person_set.get(is_main_contact=True)
        except Person.DoesNotExist:
            return None

    def get_phone(self):
        if self.get_main_contact():
            if self.get_main_contact().get_phone():
                return self.get_main_contact().get_phone()
        else:
            emps = self.person_set.all()  # Get all employees
            for emp in emps:
                if emp.get_phone():
                    phone = emp.get_phone()
                    return phone

    def get_email(self):
        if self.get_main_contact():
            if self.get_main_contact().get_email():
                return self.get_main_contact().get_email()
        else:
            emps = self.person_set.all()  # Get all employees
            for emp in emps:
                if emp.get_email():
                    email = emp.get_email()
                    return email

    def get_short_status(self):
        status = self.get_status_display().split(" ")[0]
        if status == "Active":
            color = "success"
        elif status == "Potential":
            color = "warning"
        else:
            color = "danger"
        return {"status": status, "color": color}

    @staticmethod
    def get_hot_leads(user):
        # return companies that need to be contacted

        # In a tuple: first value for new leads, second value for old leads in days
        events_frequency = {
            "ACT_LOY": (5, 45),
            "ACT_DIS": (5, 30),
            "POT_LOY": (5, 20),
            "POT_CON": (10, 45),
            "POT_UNK": (5, 45),
            "CMP_USF": (5, 45)
        }

        user_leads = Company.objects.filter(manager=user)

        hot_ids = []
        for lead in user_leads:
            if lead.status in events_frequency.keys():
                last_event_delta = timezone.now() - (lead.event_set.last().date if lead.event_set.count() else lead.date_created)
                if (timezone.now() - lead.date_created) > timedelta(days=90):
                    normal_frequency = events_frequency[lead.status][1]
                else:
                    normal_frequency = events_frequency[lead.status][0]

                if last_event_delta > timedelta(days=normal_frequency):
                    hot_ids.append(lead.id)

        print(user_leads.filter(id__in=hot_ids))
        return user_leads.filter(id__in=hot_ids)


# class CompanyStatus(models.Model):
#     status_choices = (
#         ("Unknown", "Unknown"),
#         ("Active", "Active"),
#         ("Inactive", "Inactive"),
#         ("Blocked", "Blocked"),
#         ("Competitor", "Competitor")
#     )
#     status = models.CharField(max_length=45, choices=status_choices, default=status_choices[0])
#
#     def __str__(self):
#         return self.status


class LegalForm(models.Model):
    short_form = models.CharField(max_length=15)
    long_form = models.CharField(max_length=50)

    def __str__(self):
        return self.short_form


class ContactType(models.TextChoices):
    MAIN = "MAIN", "main"
    MOBILE = "MOB", "mobile"
    WORK = "WRK", "work"
    PERSONAL = "PRS", "personal"
    PAST = "PST", "past"


class Email(models.Model):
    email = models.EmailField(max_length=255)
    type = models.CharField(max_length=4, choices=ContactType.choices, default=ContactType.MAIN)

    # foreign keys
    person = models.ForeignKey("Person", on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey("Company", on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.person.id])

    def __str__(self):
        return self.email


class Phone(models.Model):
    country_code = models.CharField(max_length=3)
    area_code = models.CharField(max_length=7)
    number = models.CharField(max_length=20)
    extension = models.CharField(max_length=20, null=True, blank=True)
    type = models.CharField(max_length=4, choices=ContactType.choices, default=ContactType.MAIN)

    # foreign keys
    # type = models.ForeignKey("ContactType", on_delete=models.SET_NULL, null=True)
    person = models.ForeignKey("Person", on_delete=models.CASCADE)
    company = models.ForeignKey("Company", on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        unique_together = (("country_code", "area_code", "number", "extension"),)

    def get_absolute_url(self):
        return reverse("leads:person-detail", args=[self.person.id])

    def __str__(self):
        phone = f"{self.country_code}{self.area_code}{self.number}"
        if self.extension:
            phone += f",{self.extension}"
        return phone
        # number_text = str(self.number)
        # return f"+{self.country_code} ({self.area_code}) {number_text[:3]}-{number_text[3:5]}-{number_text[5:]} :" \
        #        f" {self.person.first_name} {self.person.last_name} ({self.type})"

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from leads.models import Company, Person
from .models import Widget
from .context_processors import Widgets

# Below imports are for demonstration of a lower level programming
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required


# The following code is replaced by a class based view
# def dashboard(request):
#
#     context = {
#         'title': 'Dashboard',
#         'low_activity_leads': Company.objects.all(),
#         'widgets': [],
#     }
#
#     widgets = Widget.objects.filter(account=request.user)
#     for widget in widgets:
#         widget_command = "get_" + widget.title
#         if widget_command in dir(Widgets):
#             widget.value = getattr(Widgets, widget_command)()
#         context["widgets"].append(widget)
#
#     return render(request, 'dashboard/index.html', context)


class Dashboard(LoginRequiredMixin, generic.ListView):
    model = Widget
    template_name = "dashboard/index.html"
    extra_context = {
        'title': 'Dashboard'
    }

    def get_queryset(self):
        widgets = self.request.user.widgets.all()
        self.user_widgets = Widgets(self.request.user)

        for widget in widgets:
            widget_command = "get_" + widget.title.replace(" ", "_")
            if widget_command in dir(Widgets):
                widget.value = getattr(self.user_widgets, widget_command)()
                widget.type = type(widget.value).__name__
                widget.url = reverse_lazy(widget.url_path_name)
        return widgets

        # def get_context_data(self, **kwargs):
        #     ctx = super(Dashboard, self).get_context_data(**kwargs)
        #
        #     ctx['hot_leads'] = self.user_widgets.get_hot_leads()
        #     return ctx


@login_required
def settings(request):
    if request.method == "POST":
        widgets = request.POST
        for widget in widgets:
            print(len(widget))
            print(widget)
        user = request.user
    template = loader.get_template('dashboard/settings.html')
    context = {
        'widgets': Widget.objects.all()
    }
    return HttpResponse(template.render(context, request))


# TODO: work on a site search
class SiteSearch(generic.ListView):
    template_name = 'dashboard/site-search_list.html'

    def get_queryset(self):
        if 'site-search' in self.request.GET.keys():
            search_request = self.request.GET['site-search']
            object_list = Company.objects.filter(title__icontains=search_request) | Company.objects.filter(about__icontains=search_request)
        else:
            object_list = {}
        return object_list

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <!-- CSS: Bootstrap, custom -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/main.css' %}">

    <!--    Google Fonts: Roboto, Poppins-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,400&display=swap" rel="stylesheet">

    {% if title %}
    <title>Leadbook | {{ title }}</title>
    {% else %}
    <title>Leadbook</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'dashboard:home' %}" id="test">leadbook<strong class="bg-danger ml-1 pl-1 pr-1">PRO</strong></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'leads:companies' %}">Companies</a>
                    <a class="nav-item nav-link" href="{% url 'business:projects' %}">Projects</a>
                    <a class="nav-item nav-link" href="{% url 'business:task-list' %}">Tasks</a>
                    <a class="nav-item nav-link disabled" href="#">Calendar</a>
                    <a class="nav-item nav-link disabled" href="#">Reports</a>
                    {% if user.username == "admin" %}
                    <a class="nav-item nav-link" href="{% url 'admin:index' %}">Control panel</a>
                    {% endif %}
                </div>

                <!-- Search bar -->
                <form action="{% url 'dashboard:site-search' %}" class="form-inline d-flex justify-content-center md-form form-sm mt-0">
                    <input class="form-control form-control-sm ml-3 w-75" type="search" name="q" placeholder="Search" aria-label="Search">
                </form>

                <!-- Navbar Right Side -->

                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">
                        {{ user.username }}
                    </a>
                    <a href="{% url 'accounts:profile' %}"><img src="{{ user.profile_img.url}}" class="rounded-circle profile-img-nav ml-1"></a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">

            <!-- Pending Requests Card Example -->

            <div class="content-section">
                <h3>Summary</h3>
                <p class="text-muted">Highlights
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Today: <strong>{% now "F d, Y" %}</strong></li>
                    <li class="list-group-item list-group-item-light">Week: <strong>{{ global_week }}</strong></li>
                    <li class="list-group-item list-group-item-light">Currency: <strong>{{ global_currency }}</strong></li>
                    <li class="list-group-item list-group-item-light">
                        <iframe src="https://open.spotify.com/embed/album/7j8a2kSxAtenkXPim6mwUB?utm_source=generator" width="100%" height="80" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
                    </li>
                </ul>
                </p>
            </div>
            <!--            Tasks BAR-->
            {% if company.task_set.all %}
            <div class="content-section">
                <h3>Tasks</h3>
                {% include 'business/task_list_snippet.html' with task_list=company.task_set.all %}
            </div>
            {% endif %}
        </div>
    </div>
</main>

<!--Scripts: jQuery first, then Popper.js, then Bootstrap JS-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'dashboard/jquery.formset.js' %}"></script>
<!--Bootstrap tooltip jQuery-->
<script>
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();
});
</script>
<script type="text/javascript" src="{% static 'dashboard/menu_dynamic.js' %}"></script>
</body>
</body>
</html>

dashboard/templates/dashboard/form_snippet.html
{% load crispy_forms_tags %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ title }}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>

dashboard/templates/dashboard/settings.html
{% extends 'dashboard/base.html' %}
{% block content %}
<div class="content-section">
    <form method="POST" class="form-check form-switch">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Available widgets</legend>
            {% for widget in widgets %}
            <input type="checkbox" id="widget{{ forloop.counter }}" name="widget" value="{{ widget.pk }}" class="form-check-input">
            <label for="widget{{ forloop.counter }}" class="form-check-label">{{ widget }}</label><br>
            {% endfor %}
        </fieldset>
        <button class="btn btn-outline-info">Submit</button>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/site-search_list.html
{% extends 'dashboard/base.html' %}
{% block content %}
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Company</th>
        <th scope="col">Contact</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    {% for company in company_list %}
    <tr>
        <td scope="row"><a href="{% url 'leads:detail' company.pk %}" class="text-dark">{{ company.title }}, {{ company.legal_form }}</a></td>
        <td>
            {% if company.person_set.all.first.pk %}
            <a href="{% url 'leads:person-detail' company.person_set.all.first.pk %}" class="text-secondary">
                {{ company.person_set.all.first }}
            </a>
            {% endif %}
        </td>
        <td>
            {% if company.status|stringformat:"s" == "Active" %}
            <span class="text-success">{{ company.status }}</span>
            {% elif company.status|stringformat:"s" == "Inactive" %}
            <span class="text-danger">{{ company.status }}</span>
            {% else %}
            <span class="text-warning">{{ company.status }}</span>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
<hr>
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1&title={{ query_request }}">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}&title={{ query_request }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}&title={{ query_request }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}&title={{ query_request }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}&title={{ query_request }}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}&title={{ query_request }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}