business/urls.py
from django.urls import path
from .views import (ProjectList,
                    ProjectDetail,
                    DocumentCreate,
                    TaskList,
                    TaskDetail,
                    ProjectCreate,
                    EventCreate,
                    ProjectUpdate,
                    ProjectDelete,
                    EventDetail,
                    EventList,
                    EventUpdate,
                    EventDelete,
                    TaskCreate,
                    TaskUpdate,
                    TaskDelete,
                    task_set_done)

app_name = 'business'
urlpatterns = [
    path('projects/', ProjectList.as_view(), name='projects'),
    path('projects/new/', ProjectCreate.as_view(), name='project-create'),
    path('docs/new/', DocumentCreate.as_view(), name='document-create'),
    path('projects/<int:pk>/', ProjectDetail.as_view(), name='project-detail'),
    path('projects/<int:pk>/update/', ProjectUpdate.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', ProjectDelete.as_view(), name='project-delete'),
    path('events/', EventList.as_view(), name='events'),
    path('events/new/', EventCreate.as_view(), name='event-create'),
    path('events/<int:pk>/', EventDetail.as_view(), name='event-detail'),
    path('events/<int:pk>/update/', EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', EventDelete.as_view(), name='event-delete'),
    path('tasks/', TaskList.as_view(), name='task-list'),
    path('tasks/new/', TaskCreate.as_view(), name='task-create'),
    path('tasks/<int:pk>/', TaskDetail.as_view(), name='task-detail'),
    path('tasks/<int:pk>/update', TaskUpdate.as_view(), name='task-update'),
    path('tasks/<int:pk>/delete', TaskDelete.as_view(), name='task-delete'),
    path('tasks/<int:task_id>/done', task_set_done, name='task-done')
]

leadbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('leads.urls')),
    path('business/', include('business.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path
from . import views

app_name = 'leads'
urlpatterns = [
    path('', views.CompanyList.as_view(), name='companies'),
    path('new/', views.CompanyCreate.as_view(), name='companies-create'),
    path('<int:pk>/update/', views.CompanyUpdate.as_view(), name='companies-update'),
    path('<int:pk>/', views.CompanyDetail.as_view(), name='detail'),
    path('people/<int:pk>/', views.PersonDetail.as_view(), name='person-detail'),
    path('people/new/', views.PersonCreate.as_view(), name='person-create'),
    path('people/<int:pk>/update/', views.PersonUpdate.as_view(), name='person-update'),
    path('phone/new/', views.PhoneCreate.as_view(), name='phone-create'),
    path('email/new/', views.EmailCreate.as_view(), name='email-create'),
]

business/models.py
import os
from django.db import models
from django.shortcuts import reverse


class Event(models.Model):

    # Type for the task
    class EventTitle(models.TextChoices):
        PHONE = "TEL", "Phone call"
        EMAIL = "EMAIL", "Email"
        MEETING = "MEET", "Meeting"
        SKYPE = "SKYPE", "Skype call"
        CONFERENCE = "CONF", "Conference"
        TRAIN = "TRAIN", "Training"
        ORDER = "ORDER", "Order"
        INCIDENT = "INCID", "Incident"
        FAIR = "FAIR", "Trade fair"
        FORUM = "FORUM", "Forum"

    title = models.CharField(max_length=5, choices=EventTitle.choices, default=EventTitle.EMAIL)
    date = models.DateTimeField()
    description = models.TextField(max_length=5000)

    # foreign keys
    company = models.ManyToManyField("leads.Company")
    person = models.ManyToManyField("leads.Person")
    project = models.ForeignKey("Project", on_delete=models.SET_NULL, null=True, blank=True)
    manager = models.ForeignKey("accounts.User", null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering= ['date']

    def get_absolute_url(self):
        return reverse("business:event-detail", args=[self.id])

    def __str__(self):
        return f"{self.get_title_display()} with {[lead.title for lead in self.company.all()]} on {self.date.strftime('%Y-%m-%d %H:%M:%S')}"


class Task(models.Model):  # TODO: rename to "Task"

    class TaskImportance(models.TextChoices):
        URGENT = "4URG", "Urgent"
        HIGH = "3HI", "High"
        MEDIUM = "2MID", "Medium"
        LOW = "1LOW", "Low"
        FYI = "0FYI", "Info"

    task = models.CharField(max_length=45)
    description = models.TextField(max_length=5000)
    due_time = models.DateTimeField()
    done = models.BooleanField(default=False)
    importance = models.CharField(max_length=4, choices=TaskImportance.choices, default=TaskImportance.LOW)

    # test_choices = (
    #     ("TEST1", "Hello"),
    #     ("TEST2", "This"),
    #     ("TEST3", "Works"),
    #     ("TEST4", "Hello")
    # )
    # test_choices_field = models.CharField(max_length=20, null=True, choices=test_choices)

    # foreign keys
    event = models.ForeignKey("business.Event", on_delete=models.SET_NULL, null=True, blank=True)
    company = models.ForeignKey("leads.Company", on_delete=models.SET_NULL, null=True)
    person = models.ForeignKey("leads.Person", on_delete=models.SET_NULL, null=True, blank=True)
    project = models.ForeignKey("Project", on_delete=models.SET_NULL, null=True, blank=True)
    manager = models.ForeignKey("accounts.User", related_name="task_manager", null=True, on_delete=models.SET_NULL)
    executor = models.ForeignKey("accounts.User", related_name="task_executor", null=True, on_delete=models.SET_NULL)

    class Meta:
        # sort by "the date" in descending order unless
        # overridden in the query with order_by()
        ordering = ["done", "-importance", "due_time"]

    def get_absolute_url(self):
        return reverse("business:task-detail", args=[self.id])

    def __str__(self):
        return self.task


class Project(models.Model):
    code = models.CharField(max_length=100, unique=True)
    location = models.CharField(max_length=100, help_text="City of the project")
    short_description = models.CharField(max_length=100, help_text="Short description like facility's title")
    description = models.TextField(max_length=5000)
    volume = models.IntegerField(null=True, blank=True, help_text="Estimated project volume in euros")
    registry_date = models.DateTimeField()
    fulfilment_date = models.DateTimeField(null=True, blank=True)

    # foreign keys
    manager = models.ForeignKey("accounts.User", null=True, on_delete=models.SET_NULL)
    company = models.ManyToManyField("leads.Company", through="ProjectCompany")
    status = models.ForeignKey("ProjectStatus", on_delete=models.SET_NULL, null=True)
    stage = models.ForeignKey("ProjectStage", on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["registry_date"]

    def get_absolute_url(self):
        return reverse("business:project-detail", args=[self.id])

    def __str__(self):
        return f"{self.code} {self.location} ({self.short_description})"


class ProjectCompany(models.Model):

    class RoleChoices(models.TextChoices):
        CONTRACTOR = "CTR", "Contractor"
        INTEGRATOR = "INT", "Integrator"
        END_USER = "EUS", "End User"
        PARTNER = "PRT", "Partner"

    role = models.CharField(max_length=3, choices=RoleChoices.choices, default=str(RoleChoices.CONTRACTOR))  # TODO: find out why it works only with str()
    project = models.ForeignKey("business.Project", on_delete=models.CASCADE)
    company = models.ForeignKey("leads.Company", on_delete=models.CASCADE)

    class Meta:
        ordering = ["-project__registry_date"]

    def __str__(self):
        return f"{self.company}: {self.role} ({self.project})"


# TODO: change project status and stage to choice class
class ProjectStatus(models.Model):
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.status


class ProjectStage(models.Model):
    stage = models.CharField(max_length=100)

    def __str__(self):
        return self.stage


def project_file_path(instance, filename):
    print(instance, filename)
    return f"projects/{instance.project.pk}/documents/{filename}"


class Document(models.Model):
    project = models.ForeignKey("Project", on_delete=models.CASCADE)
    document = models.FileField(upload_to=project_file_path)
    description = models.CharField(max_length=500)

    def get_absolute_url(self):
        return reverse("business:project-detail", args=[self.project.id])

    @property
    def filename(self):
        return os.path.basename(self.document.name)

    @property
    def filetype(self):
        return os.path.splitext(self.document.name)[1][1:]

business/forms.py
from django.forms import ModelForm, inlineformset_factory, MultipleChoiceField, DateTimeInput
from .models import Event, Project, ProjectCompany


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'
        widgets = {
            "date": DateTimeInput(
                attrs={'type': 'datetime-local'},
            )
        }


class ProjectCreateForm(ModelForm):
    class Meta:
        model = Project
        exclude = ["company"]
        widgets = {
            "company": MultipleChoiceField
        }


class ProjectCompanyForm(ModelForm):
    class Meta:
        model = ProjectCompany
        fields = ("company", "role")


ProjectInlineFormSet = inlineformset_factory(
    Project,
    ProjectCompany,
    form=ProjectCompanyForm,
    extra=1,
    can_delete=True,
    can_order=False
)

business/templates/business/document_form.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ title }}</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Save</button>
        </div>
    </form>
</div>
{% endblock content %}

business/templates/business/project_detail.html
{% extends 'dashboard/base.html' %}
{% block content %}
<article class="media content-section">
    <!--        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">-->
    <div class="media-body">
        <div class="d-flex bd-highlight">
            <div class="pt-2 pr-2 pb-2 flex-grow-1 bd-highlight">
                <h3>{{ project }}</h3>
            </div>
            <div class="p-2 bd-highlight">
                <a href="{% url 'business:project-update' project.pk %}" class="btn btn-outline-info float-right">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                    </svg>
                </a>
                <a href="{% url 'business:project-delete' project.pk %}" class="btn  btn-outline-danger float-right">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                    </svg>
                </a>
            </div>
        </div>
        {% load humanize %}
        {% if project.volume %}
        <small><strong class="text-success">€ {{ project.volume|intcomma }}</strong></small>
        {% endif %}
        <div class="text-muted">
            {% if project.projectcompany_set.all %}
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-building mr-1" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694L1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
                <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
            </svg>
            {% for participation in project.projectcompany_set.all %}
            <a href="{% url 'leads:detail' participation.company.pk %}" class="text-secondary">{{ participation.company }} ({{ participation.get_role_display }})</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            {% endif %}
        </div>
        <div class="progress mt-3 mb-3">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="70"
                 aria-valuemin="0" aria-valuemax="100" style="width:50%">
                50% Complete
            </div>
        </div>
        {{ project.description|linebreaks }}
        <strong>Documents</strong>
        <a href="{% url 'business:document-create' %}?project={{ project.id }}" class="ml-2" type="submit">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </a>
        <ul class="list-unstyled pt-2">
            {% for record in project.document_set.all %}
            <li class="file">
                <a href="{{ record.document.url }}" target="_blank" class="text-secondary">
                    <i class="{{ record.filetype }}"></i>
                    {{ record.filename }}
                </a>
            </li>
            {% endfor %}
        </ul>
        <hr>
        <!--            <table class="table">-->
        <!--                <thead>-->
        <!--                <tr>-->
        <!--                    <th scope="col">Product group</th>-->
        <!--                    <th scope="col">Discount</th>-->
        <!--                    <th scope="col">Status</th>-->
        <!--                    &lt;!&ndash;                      <th scope="col">Class</th>&ndash;&gt;-->
        <!--                </tr>-->
        <!--                </thead>-->
        <!--                <tbody>-->
        <!--                {% for discount in company.discounts.all %}-->
        <!--                <tr>-->
        <!--                    <td>{{ discount.product_group.description }}</td>-->
        <!--                    <th scope="row">{{ discount.value }} %</th>-->
        <!--                    <td>{{ discount.status }}({{ discount.turnover_class }})</td>-->
        <!--                    &lt;!&ndash;                  <td>{{ discount.turnover_class }}</td>&ndash;&gt;-->
        <!--                </tr>-->
        <!--                {% endfor %}-->
        <!--                </tbody>-->
        <!--            </table>-->
        <!--            <hr>-->
        <strong>History</strong>
        <a href="{% url 'business:event-create' %}?project={{ project.id }}&company={{ project.company_contractor.id }}" class="ml-2" type="submit">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
            </svg>
        </a>
        {% if project.event_set.all %}
        <div class="container">
            <div class="row">
                <div class="mt-1 mr-5">
                    <ul class="timeline">
                        {% for event in project.event_set.all reversed %}
                        <li>
                            <a href="{% url 'business:event-detail' event.pk %}">{{ event.get_title_display }}</a>
                            <a href="{% url 'business:event-update' event.pk %}" class="ml-3 text-info">
                                <svg width="0.9em" height="0.9em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                                </svg>
                            </a>
                            <a href="{% url 'business:event-delete' event.pk %}" class="ml-3 text-danger">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </a>
                            <span class="float-right text-muted">{{ event.date|date:'F d, Y' }}</span>
                            <p>{{ event.description|linebreaks }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <!--                <ul class="list-group pt-2">-->
        <!--                  {% for event in company.event_set.all reversed %}-->
        <!--                    <span class="text-muted mb-1">{{ event.date|date:'F d, Y' }} - {{ event.task }}</span>-->
        <!--                    <li class="list-group-item">-->
        <!--                        {{ event.description }}-->
        <!--                    </li>-->
        <!--                    <br>-->
        <!--                  {% endfor %}-->
        <!--                </ul>-->
        {% endif %}
</article>
<!--    {% if user == object.author %}-->
<div>
    <a class="btn btn-outline-secondary" href="#">Update</a>
    <a class="btn btn-outline-danger" href="#">Delete</a>
</div>
<!--    {% endif %}-->
{% endblock content %}

business/templates/business/project_list.html
{% extends 'dashboard/base.html' %}
{% block content %}
<form method="GET" class="form-inline d-flex md-form mr-auto mb-2 form-sm mt-0">
    <input type="search" id="site-search" name="q" placeholder="Search" {% if q %} value="{{ q }}"{% endif %} aria-label="Search" class="form-control flex-fill w-auto">
    <a href="{% url 'business:project-create' %}" class="btn btn-outline-info ml-2" data-toggle="tooltip" data-placement="right" title="Add new project">
        create
    </a>
</form>
<table class="table table-hover content-section">
    <thead>
    <tr>
        <th scope="col">Code</th>
        <th scope="col">Contractor</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    {% for project in project_list %}
    <tr>
        <td><a href="{% url 'business:project-detail' project.pk %}" class="text-dark">{{ project }}</a></td>
        <td>
            {% if project.projectcompany_set.first %}
            {% for partnership in project.projectcompany_set.all %}
            <a class="text-muted" href="{% url 'leads:detail' partnership.company.pk %}">{{ partnership.company }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            {% endif %}
        </td>
        <td>
            {% if project.status|stringformat:"s" == "Completed" %}
            <span class="text-success">{{ project.status }}</span>
            {% elif project.status|stringformat:"s" == "Canceled" %}
            <span class="text-danger">{{ project.status }}</span>
            {% else %}
            <span class="text-warning">{{ project.status }}</span>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
<hr>
{% if page_obj.has_previous %}
<a class="btn btn-outline-secondary mb-4" href="?page=1&q={{ q }}">First</a>
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.previous_page_number }}&q={{ q }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-secondary mb-4" href="?page={{ num }}&q={{ q }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-secondary mb-4" href="?page={{ num }}&q={{ q }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.next_page_number }}&q={{ q }}">Next</a>
<a class="btn btn-outline-secondary mb-4" href="?page={{ page_obj.paginator.num_pages }}&q={{ q }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}

business/templates/business/task_list.html
{% extends 'dashboard/base.html' %}
{% block content %}
<form method="GET" class="form-inline d-flex md-form mr-auto mb-2 form-sm mt-0">
    <input type="search" id="site-search" name="q" placeholder="Search" {% if q %} value="{{ q }}"{% endif %} aria-label="Search" class="form-control flex-fill w-auto">
    <a href="{% url 'business:project-create' %}" class="btn btn-outline-info ml-2" data-toggle="tooltip" data-placement="right" title="Add new project">
        create
    </a>
</form>
{% include 'business/task_list_snippet.html' %}
{% endblock content %}